version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: postoffice
      MYSQL_USER: adityap
      MYSQL_PASSWORD: aditya
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./postoffice.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge
